ConfirmationCodesService:
    Db:
        LogsConnString:
            settings-key: ConfirmationCodesService-LogsConnString
            types:
                - AzureTableStorage
        ClientPersonalInfoConnString:
            settings-key: PersonalInfoConnString
            types:
                - AzureTableStorage
        Google2FaConnString:
            settings-key: ConfirmationCodesService-Google2FaConnString
            types:
                - AzureTableStorage
    DeploymentSettings:
        IsProduction:
            settings-key: ConfirmationCodesService-IsProduction
    SupportToolsSettings:
        PriorityCodeExpirationInterval:
            settings-key: ConfirmationCodesService-PriorityCodeExpirationInterval
    Google2FaConfirmationMaxTries:
        settings-key: ConfirmationCodesService-Google2FaConfirmationMaxTries
    Google2FaSetupDisabled:
        settings-key: ConfirmationCodesService-Google2FaSetupDisabled

ClientAccountServiceClient:
    ServiceUrl:
        settings-key: ClientAccountServiceUrl

MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl
        
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName:
            settings-key: SlackQueueName

SagasRabbitMq:
  RabbitConnectionString:
    settings-key: SagasRabbitMqConnStr
    types:
      - RabbitMq

RedisConfiguration:
  ConnectionString:
    settings-key: RedisClientAccountConnString

SmsNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SmsNotificationsAzureQueueConnString
    QueueName:
      settings-key: SmsNotificationsAzureQueueName